#!/bin/bash
set -e

SMCL_BIN=${SMCL_BIN:-`pwd`/dist/smcl_linux_amd64}

function startCommand {
    set +e
    COMMIT=$(git log --pretty=oneline -n1 | grep "version bump to")
    if [ $? -eq 0 ]; then
        echo "skipping release: this is a version bump."
        exit 1000
    fi
    set -e
    NEXT_VERSION=$($SMCL_BIN --dir `pwd` next-version)
    $SMCL_BIN --dir `pwd` generate
    git commit -am "version bump to $NEXT_VERSION"
    git tag $NEXT_VERSION
    GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git push origin --tags master
}

function help {
    cat << "EOF"
Usage: ./kitt release 00_generate

ENV VARIABLES:
    * SMCL_BIN
    
EOF
}

function init {
    echo $@
    # shellcheck disable=SC2194
    case "$1" in
        --help)
            help
            exit 0
            ;;
        *)
            startCommand
            exit 0
    esac
}
init $@

